### ISSUE TITLE
still it is not clear how to use web based app

### ISSUE THREAD

**Issue by Sandy4321** [pablobernabeu/Experimental-data-simulation#2]
still it is not clear how to use web based app
can you share instructions from 0 to end
is it enough to click on download file?
![image](https://user-images.githubusercontent.com/11426119/89061801-59b44280-d333-11ea-9618-774ff361a45d.png)

**Comment by pablobernabeu** [comment]
Hi @Sandy4321, thanks a lot for the heads-up! I'll add some screenshots soon.

**Comment by Sandy4321** [comment]
Great thanks 😊
